### ISSUE TITLE
Which system libs do you need to build the GUI?

### ISSUE THREAD

**Issue by LuceusXylian** [LoipesMas/accord#3]
I did installed:
apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libcairo2-dev libglib2.0

Still getting many missing syslibs errors. 
..

Many system libs are missing by default so please state them in the README.md

**Comment by LuceusXylian** [comment]
OK, I did now read the driud README. But still please add this line: 

sudo apt-get install libgtk-3-dev

**Comment by LoipesMas** [comment]
I'll add this, thanks!
